apiVersion: v1
kind: Service
metadata:
  name: customerapiservice
  labels:
    app: customerapiservice
spec:
  ports:
  - name: http
    protocol: TCP
    port: 9001
    targetPort: 9001
  selector:
    app: customerapiservice
  type: ClusterIP  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customerapiservice
  labels:
    app: customerapiservice
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: customerapiservice
    spec:
      containers:
      - image: acrplayground01.azurecr.io/customers
        name: customerapiservice
        ports:
        - containerPort: 9001
          name: http
        resources:
          limits:
            cpu: 900m
          requests:
            cpu: 100m
      imagePullSecrets:
        - name: regsecret
---      
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: customerapiservice
spec:
  scaleTargetRef:
    kind: Deployment
    name: customerapiservice
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
