apiVersion: v1
kind: Service
metadata:
  name: apigateway
  labels:
    app: apigateway
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9000
  selector:
    app: apigateway
  type: LoadBalancer  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app: apigateway
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - image: acrplayground01.azurecr.io/api
        name: apigateway
        ports:
        - containerPort: 9000
          name: http
        resources:
          limits:
            cpu: 900m
          requests:
            cpu: 100m
      imagePullSecrets:
        - name: regsecret
---      
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: apigateway
spec:
  scaleTargetRef:
    kind: Deployment
    name: apigateway
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
